services:
  postgres:
    image: postgres:15-alpine
    container_name: codexa-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codexa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:3.7.0
    container_name: codexa-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk

  auth-service:
    build:
      context: .
      dockerfile: auth-service/DockerFile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/codexa
      - NODE_ENV=development
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - postgres
      - kafka

  problem-service:
    build:
      context: .
      dockerfile: problem-service/DockerFile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/codexa
      - NODE_ENV=development
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - postgres
      - kafka

  utils-service:
    build:
      context: .
      dockerfile: utils-service/DockerFile
    ports:
      - "3003:3003"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/codexa
      - NODE_ENV=development
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - postgres
      - kafka

volumes:
  postgres_data:
