services:
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: codexa-postgres
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: codexa
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:3.7.0
    container_name: codexa-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk

  auth-service:
    build:
      context: .
      dockerfile: auth-service/DockerFile
      args:
        - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=development
      - KAFKA_BROKERS=kafka:9092
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - FILE_UPLOAD_SERVICE_URL=http://utils-service:3001
    depends_on:
      - kafka
    restart: always

  utils-service:
    build:
      context: .
      dockerfile: utils-service/DockerFile
      args:
        - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=development
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_GROUP_ID=utils-service-group
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    depends_on:
      - kafka
    restart: always
  problem-service:
    build:
      context: .
      dockerfile: problem-service/DockerFile
      args:
        - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=development
      - KAFKA_BROKERS=kafka:9092
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
    depends_on:
      - kafka
    restart: always

volumes:
  postgres_data:
